- go.mod
- go.sum
- internal/tests/suite_setup_test.go
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Minor fixes

- main.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Closes https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/31
> Add missed required registry chain elements and update sdk-vpp

- go.mod
- go.sum
> Update govpp to latest

- .golangci.yml
- internal/imports/imports_linux.go
- internal/vppinit/vppinit.go
This PR is related to AWS integration
> Add arp entries

- internal/vppinit/vppinit.go
Issue: https://github.com/networkservicemesh/integration-k8s-gke/issues/22
> Add neighbors that in REACHABLE state

- .golangci.yml
- internal/vppinit/vppinit.go
Related issue: https://github.com/networkservicemesh/integration-k8s-packet/issues/68
> Fix ip family mismatch for routes

- internal/imports/imports_linux.go
- main.go
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
Closes networkservicemesh/deployments-k8s#1929
> feat: Add spire certs updating for cmd-forwarder-vpp

- go.mod
- go.sum
- internal/tests/suite_kernel_test.go
> Manual sdk update

- .golangci.yml
- internal/imports/gen.go
- internal/tests/ns/client.go
- internal/tests/ns/server.go
- internal/tests/suite_combinatronics_test.go
- internal/tests/suite_healthcheck_test.go
- internal/tests/suite_kernel_test.go
- internal/tests/suite_memif_test.go
- internal/tests/suite_setup_test.go
- internal/tests/suite_test.go
- internal/tests/suite_util_test.go
- internal/tests/suite_vxlan_test.go
- internal/tests/suite_wireguard_test.go
- internal/vppinit/acl.go
- internal/vppinit/vppinit.go
- main.go
Sets default token timeout to `10m`.
networkservicemesh/deployments-k8s#906
> [deployments-k8s#906] Decrease default token timeout to 10m

- Dockerfile
- go.mod
- go.sum
> Upgrade to VPP v21.06

- internal/tests/suite_memif_test.go
https://github.com/networkservicemesh/deployments-k8s/issues/2822
> Add sendFD to memif client in tests

- internal/imports/imports_linux.go
- main.go
Fixes: #344
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
> Add InitJaeger to main

- Dockerfile
- internal/tests/suite_setup_test.go
> qfix: Remove debug artifacts from last merge

- internal/config/config.go
> feat: Add p2p capability

- go.mod
- go.sum
- internal/config/config.go
- internal/xconnectns/server.go
- main.go
https://github.com/networkservicemesh/integration-k8s-kind/runs/4171588411?check_suite_focus=true
Closes https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/392
> qfix: Add dialTimeout for cmd-forwarder-vpp

- main.go
> Update grpc options

- go.mod
- go.sum
- internal/imports/imports_linux.go
- internal/xconnectns/server.go
Requires for https://github.com/networkservicemesh/integration-k8s-packet/pull/165
> qfx: Update `cmd-forwarder-vpp` to latest sdk-sriov

- go.mod
- go.sum
- internal/config/config.go
- internal/devicecfg/config.yml
- internal/devicecfg/devicecfg.go
- internal/devicecfg/devicecfg_test.go
- internal/vppinit/links.go
- internal/xconnectns/server.go
- main.go
Add domain pool mapping
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
> Add vlan remote mechanism support (see networkservicemesh/sdk-vpp#399)

- go.mod
- go.sum
- internal/tests/suite_combinatronics_test.go
- internal/tests/suite_healthcheck_test.go
- main.go
Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
closes https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/426
>  manual sdk update

- .github/workflows/automerge.yaml
Signed-off-by: Oleg Solodkov <oleg.solodkov@xored.com>
> Added autoresolving conflicts in go.mod

- go.mod
- go.sum
Closes: https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/482
> Manual sdk-vpp update

- internal/imports/imports_linux.go
- main.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Related to networkservicemesh/integration-k8s-kind#565
> qfix: Add missed sendfd registry client

- internal/vppinit/vppinit.go
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> MTU fix for cmd-forwarder-vpp#557

- Dockerfile
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Updated to base image to get iptables

- .github/workflows/ci.yaml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
> Add config_file path to yamllint job in CI workflow

- go.mod
- go.sum
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
> Update to the latest sdk

- go.mod
- go.sum
…k-vpp@main
PR link: https://github.com/networkservicemesh/sdk-vpp/pull/646
Commit: 292a9b1
Author: Network Service Mesh Bot
Date: 2022-09-23 05:47:03 -0500
Message:
- Update go.mod and go.sum to latest version from networkservicemesh/sd…
Signed-off-by: NSMBot <nsmbot@networkservicmesh.io>
> Manual Update from update/networkservicemesh/sdk-vpp 

- Dockerfile
- go.mod
- go.sum
> Update govpp (wireguard ipv6)

- Dockerfile
- go.mod
- go.sum
> Update govpp (wireguard ipv6 checksum)

- internal/imports/imports_linux.go
- internal/vppinit/vppinit.go
> Disable IPv6 RA

- Dockerfile
- go.mod
- go.sum
- internal/tests/suite_setup_test.go
- internal/vppinit/acl.go
- internal/vppinit/vppinit.go
VPP version: e416893a597959509c7f667c140c271c0bb78c14
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/802
> Update vpp version

- main.go
Issue: https://github.com/networkservicemesh/sdk/issues/1441
Added opentelemetry grpc interceptors
> Fix grpc options

- internal/vppinit/acl.go
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/864
> Fix ICMPv6 ingress ACL rules

- go.mod
- go.sum
- internal/imports/imports_linux.go
- internal/vppinit/vppinit.go
Issue: https://github.com/networkservicemesh/integration-k8s-aws/issues/356
Issue: https://github.com/networkservicemesh/integration-k8s-aks/issues/282
We need additional AF_XDP settings for AWS, AKS
> Setting up AF_XDP for public clusters

- internal/tests/suite_healthcheck_test.go
- internal/tests/suite_setup_test.go
- main.go
https://github.com/networkservicemesh/sdk/issues/1455
> Delete grpc.WithBlock() and grpc.WaitForReady(true) options

- internal/tests/suite_healthcheck_test.go
- internal/tests/suite_setup_test.go
- main.go
This reverts commit 2d3d13c513595c133e9d0f44c8edae6e0807e01c.
> Revert "Delete grpc.WithBlock() and grpc.WaitForReady(true) options (#917)"

- internal/tests/suite_healthcheck_test.go
Fix linter error in https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/919
> Fix copyright dates in internal/tests/suite_healthcheck_test.go

- main.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9726
> Enable tracing

- Dockerfile
- main.go
https://github.com/networkservicemesh/cmd-template/issues/123
> Update Spire version and make Dockerfile support multi-arch build

- README.md
- go.mod
- go.sum
- internal/config/config.go
- internal/imports/imports_linux.go
- internal/tests/suite_ipsec_test.go
- internal/tests/suite_memif_test.go
- internal/tests/suite_setup_test.go
- internal/tests/suite_test.go
- internal/tests/suite_wireguard_test.go
- main.go
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1133
> Update vpphelper manually

- Dockerfile
- go.mod
- go.sum
- internal/tests/suite_combinatronics_test.go
> VPP v24.10 uplift

- internal/config/config.go
- main.go
This pull request updates the copyrights section of the main.go file.
> Update copyrights section of main.go

- README.md
- internal/config/config.go
- internal/imports/imports_linux.go
- internal/xconnectns/server.go
- main.go
Increase default dial timeout, add dial maximum delay 
Related issue: networkservicemesh/deployments-k8s/issues/13484
> Modify NSM internal GRPC connection parameters
