networkservicemesh/cmd-forwarder-vpp

internal/tests/ns/client.go, internal/tests/ns/server.go
Fix failing Docker tests with message like this:
```
suite_combinatronics_test.go:125: 
Error Trace:	suite_combinatronics_test.go:125
Error:      	Received unexpected error:
Link not found
unable to find interface "ns-e4dc57ba-cc6"
```
Resolves #64
Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
=> Fix tests failing on netns switching

internal/imports/imports_linux.go, internal/vppinit/acl.go, internal/vppinit/vppinit.go
When binding to the tunnel interface with AF_PACKET, we should *not*
respond to anything except valid tunnel packets.
vppinit does this by applying a DENYALL ACL.
Individual tunnel chain elements are then responsible for poking a 'hole'
in the DENYALL ACL for themselves.  See:
https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/mechanisms/vxlan/vxlanacl
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Block AF_PACKET bound tunnel interface from communication

internal/tests/suite_kernel_test.go
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/254
Needed because of:
https://github.com/networkservicemesh/sdk/pull/1014
https://github.com/networkservicemesh/api/pull/108
=> Fix kernel endpoint verifying in docker tests

Dockerfile, go.mod, go.sum
Closes: https://github.com/networkservicemesh/sdk-vpp/issues/348
=> Update govpp version

Dockerfile, go.mod, go.sum, internal/config/config.go, internal/imports/imports_linux.go, internal/tests/suite_combinatronics_test.go, internal/tests/suite_setup_test.go, internal/tests/suite_test.go, internal/xconnectns/server.go, main.go
=> qfix: Manually update to latest sdk changes

internal/tests/suite_combinatronics_test.go, internal/tests/suite_kernel_test.go, internal/tests/suite_setup_test.go, internal/tests/suite_util_test.go
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
=> Enable remote docker tests

internal/config/config.go
`50 ms` is not enough for some cases
```
...
Feb  5 20:06:30.795[37m [TRAC] [id:21a9d757-c9c4-4737-8f3e-c64377b447db] [type:networkService] [0m(39)                                       ⎆ sdk/pkg/networkservice/common/null/nullClient.Request()
Feb  5 20:06:30.795[37m [TRAC] [id:21a9d757-c9c4-4737-8f3e-c64377b447db] [type:networkService] [0m(40)                                        ⎆ sdk/pkg/networkservice/common/dial/dialClient.Request()
Feb  5 20:06:30.846[31m [ERRO] [id:21a9d757-c9c4-4737-8f3e-c64377b447db] [type:networkService] [0m(40.1)                                          can not dial to unix:///proc/1/fd/24, err failed to dial unix:///proc/1/fd/24: context deadline exceeded. Deleting clientconn...
Feb  5 20:06:30.846[31m [ERRO] [id:21a9d757-c9c4-4737-8f3e-c64377b447db] …
```
=> [qfix] Increase dial timeout

internal/config/config.go
Closes: https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/537
=> [qfix] Change default VppAPISocket path

internal/tests/suite_kernel_test.go, internal/vppinit/vppinit.go
- MTU fix for cmd-forwarder-vpp#557
- Testing for MTU fix for cmd-forwarder-vpp#557
=> Test for MTU fix for cmd-forwarder-vpp#557

main.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
At this moment all applications spam trace logs even if log level is not trace.
Enable tracing only and only if log level is trace.
=> fix: Enable tracing only and only if log level is trace

internal/vppinit/links.go
Related issue: #658
Any interface known to host and contained by device selector file will be set up.
In case of failure during interface setup a warning is logged.
The remaining devices will be processed.
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Fix issue: device selector containing interface not known to host

go.mod, go.sum, internal/imports/imports_linux.go, internal/xconnectns/options.go, internal/xconnectns/server.go, main.go
Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>
=> Enable auth MonitorConnectionServer

internal/vppinit/vppinit.go
VPP, being a router, presumes that any IPv6 enabled interface should,
by default, be sending IPv6 Router Announcements (RAs).
In our case, this is an incorrect behavior.
In the past we had attempted using:
'ip6 nd host-%s ra-cease'
this did not work as expected for two reasons:
1.  It was done before assigning an IPv6 address to the interface.
Because of this the interface does not yet have IPv6 enabled,
and therefore the 'ip6 nd host-%s ra-cease' has no effect.
2.  'ip6 nd host-%s ra-cease' only precluded repetition of RAs
after the interface is up.  Initial RAs are still sent.
This can be fixed by adding 'ra-suppress'
So in short, we use:
'enable ip6 interface host-%s'
'ip6 nd host-%s ra-cease ra-suppress'
which disables any sending of RAs from the interface prior to it
being 'upped'. …
=> Final fix to disable IPv6 RA when NSM_TUNNEL_IP is IPv6

go.mod, go.sum, internal/tests/suite_memif_test.go
Closes: https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/776
Issue: https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/136
=> Update sdk-vpp with latest memif changes

internal/config/config.go, main.go
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
=> Add custom policies support

internal/vppinit/vppinit.go
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/841
The frame size that was used in release 1.7.1 was set
=> Set Rx/TxFrameSize for af_packet interface

main.go
`grpc.WithBlock()` was missed in this PR - https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/854
=> Added missed grpc option

Dockerfile
This allows to use `x86_64` or `aarch64`
=> Fix Dockerfile for ARM64

internal/tests/suite_setup_test.go, internal/vppinit/config.go, internal/vppinit/config_arm_arm64.go, main.go
Got an error on ARM arch:
```
Jul 12 22:52:20.964 [INFO] [cmd:vpp] vpp[31987]: vlib_buffer_main_init_numa_alloc: buffer size (4224) is greater than page size (4096)
```
In this PR we change the `default data-size` to `3712`, because ARM uses additional 64 bytes
=> Use another vpp config for ARM

internal/vppinit/vppinit.go
Cilium CNI plugin uses /32 for hosts addresses. 
When we inject the host interface to VPP, we try to resolve the gateway MAC using ARP Request. But when we receive the ARP reply, VPP cannot handle it, because:
```
00:03:50:190782: af-packet-input
af_packet: hw_if_index 1 rx-queue 0 next-index 4
tpacket2_hdr:
status 0x1 len 42 snaplen 42 mac 66 net 80
sec 0x6565ca18 nsec 0xc19ad4 vlan 0 vlan_tpid 0
vnet-hdr:
flags 0x00 gso_type 0x00 hdr_len 0
gso_size 0 csum_start 0 csum_offset 0
00:03:50:190793: ethernet-input
ARP: 22:88:cd:e1:98:ba -> 82:9f:51:46:12:92
00:03:50:190800: arp-input
reply, type ethernet/IP4, address size 6/4
22:88:cd:e1:98:ba/10.244.2.250 -> 82:9f:51:46:12:92/10.244.2.154
00:03:50:190803: arp-reply
reply, type ethernet/IP4, address size 6/4
22:88:cd:e1:98:ba/10.244.2.250 -> …
```
=> Fix neighbor discovering

internal/config/config.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/11372
We checked that for 30 clients on one node, about `500ms` dial timeout is required. Set to `750ms` here as a fallback.
=> Increase dial timeout

README.md, internal/config/config.go, internal/imports/imports_linux.go, main.go
Added a section in the main for initializing Prometheus and extended the config with the required variables.
https://github.com/networkservicemesh/sdk/issues/1652
=> Add an option to expose Prometheus metrics via http/s in the forwarder-vpp

Dockerfile
Delve 1.21.1 is no longer works with go 1.23
Signed-off-by: Lajos Katona <lajos.katona@est.tech>
=> New delve version (1.23.1)
